// Code generated by github.com/algorand/msgp DO NOT EDIT.

package tests

import (
	"github.com/algorand/msgp/msgp"
)

// The following msgp objects are implemented in this file:
// AnyDeclNeighbor
//        |-----> (*) MarshalMsg
//        |-----> (*) CanMarshalMsg
//        |-----> (*) UnmarshalMsg
//        |-----> (*) UnmarshalMsgWithState
//        |-----> (*) CanUnmarshalMsg
//        |-----> (*) Msgsize
//        |-----> (*) MsgIsZero
//        |-----> AnyDeclNeighborMaxSize()
//

// MarshalMsg implements msgp.Marshaler
func (z *AnyDeclNeighbor) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 3 bits */
	if (*z).Count == 0 {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if (*z).Name == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len != 0 {
		if (zb0001Mask & 0x2) == 0 { // if not empty
			// string "c"
			o = append(o, 0xa1, 0x63)
			o = msgp.AppendUint64(o, (*z).Count)
		}
		if (zb0001Mask & 0x4) == 0 { // if not empty
			// string "n"
			o = append(o, 0xa1, 0x6e)
			o = msgp.AppendString(o, (*z).Name)
		}
	}
	return
}

func (_ *AnyDeclNeighbor) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(*AnyDeclNeighbor)
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *AnyDeclNeighbor) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var field []byte
	_ = field
	var zb0001 int
	var zb0002 bool
	zb0001, zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
	if _, ok := err.(msgp.TypeError); ok {
		zb0001, zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0001 > 0 {
			zb0001--
			(*z).Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "Name")
				return
			}
		}
		if zb0001 > 0 {
			zb0001--
			(*z).Count, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "Count")
				return
			}
		}
		if zb0001 > 0 {
			err = msgp.ErrTooManyArrayFields(zb0001)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array")
				return
			}
		}
	} else {
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0002 {
			(*z) = AnyDeclNeighbor{}
		}
		for zb0001 > 0 {
			zb0001--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
			switch string(field) {
			case "n":
				(*z).Name, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Name")
					return
				}
			case "c":
				(*z).Count, bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Count")
					return
				}
			default:
				err = msgp.ErrNoField(string(field))
				if err != nil {
					err = msgp.WrapError(err)
					return
				}
			}
		}
	}
	o = bts
	return
}

func (z *AnyDeclNeighbor) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *AnyDeclNeighbor) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*AnyDeclNeighbor)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *AnyDeclNeighbor) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len((*z).Name) + 2 + msgp.Uint64Size
	return
}

// MsgIsZero returns whether this is a zero value
func (z *AnyDeclNeighbor) MsgIsZero() bool {
	return ((*z).Name == "") && ((*z).Count == 0)
}

// AnyDeclNeighborMaxSize returns a maximum valid message size for this message type
func AnyDeclNeighborMaxSize() (s int) {
	s = 1 + 2
	panic("Unable to determine max size: String type z.Name is unbounded")
}
