// Code generated by github.com/algorand/msgp DO NOT EDIT.

package tests

import (
	"github.com/algorand/msgp/msgp"
)

// The following msgp objects are implemented in this file:
// ArgsHolder
//      |-----> (*) MarshalMsg
//      |-----> (*) CanMarshalMsg
//      |-----> (*) UnmarshalMsg
//      |-----> (*) UnmarshalMsgWithState
//      |-----> (*) CanUnmarshalMsg
//      |-----> (*) Msgsize
//      |-----> (*) MsgIsZero
//      |-----> ArgsHolderMaxSize()
//
// BoundedArgs
//      |-----> MarshalMsg
//      |-----> CanMarshalMsg
//      |-----> (*) UnmarshalMsg
//      |-----> (*) UnmarshalMsgWithState
//      |-----> (*) CanUnmarshalMsg
//      |-----> Msgsize
//      |-----> MsgIsZero
//      |-----> BoundedArgsMaxSize()
//
// TotalBoundedArgs
//         |-----> MarshalMsg
//         |-----> CanMarshalMsg
//         |-----> (*) UnmarshalMsg
//         |-----> (*) UnmarshalMsgWithState
//         |-----> (*) CanUnmarshalMsg
//         |-----> Msgsize
//         |-----> MsgIsZero
//         |-----> TotalBoundedArgsMaxSize()
//

// MarshalMsg implements msgp.Marshaler
func (z *ArgsHolder) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0002Len := uint32(1)
	var zb0002Mask uint8 /* 2 bits */
	if len((*z).Args) == 0 {
		zb0002Len--
		zb0002Mask |= 0x2
	}
	// variable map header, size zb0002Len
	o = append(o, 0x80|uint8(zb0002Len))
	if zb0002Len != 0 {
		if (zb0002Mask & 0x2) == 0 { // if not empty
			// string "a"
			o = append(o, 0xa1, 0x61)
			if (*z).Args == nil {
				o = msgp.AppendNil(o)
			} else {
				o = msgp.AppendArrayHeader(o, uint32(len((*z).Args)))
			}
			for zb0001 := range (*z).Args {
				o = msgp.AppendBytes(o, (*z).Args[zb0001])
			}
		}
	}
	return
}

func (_ *ArgsHolder) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(*ArgsHolder)
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ArgsHolder) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var field []byte
	_ = field
	var zb0002 int
	var zb0003 bool
	zb0002, zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0003 {
		(*z) = ArgsHolder{}
	}
	for zb0002 > 0 {
		zb0002--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch string(field) {
		case "a":
			var zb0004 int
			var zb0005 bool
			zb0004, zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
			if zb0004 > argCount {
				err = msgp.ErrOverflow(uint64(zb0004), uint64(argCount))
				err = msgp.WrapError(err, "Args")
				return
			}
			if zb0005 {
				(*z).Args = nil
			} else if (*z).Args != nil && cap((*z).Args) >= zb0004 {
				(*z).Args = ((*z).Args)[:zb0004]
			} else {
				(*z).Args = make(TotalBoundedArgs, zb0004)
			}
			for zb0001 := range (*z).Args {
				var zb0006 int
				zb0006, err = msgp.ReadBytesBytesHeader(bts)
				if err != nil {
					err = msgp.WrapError(err, "Args", zb0001)
					return
				}
				if zb0006 > argMaxSize {
					err = msgp.ErrOverflow(uint64(zb0006), uint64(argMaxSize))
					return
				}
				(*z).Args[zb0001], bts, err = msgp.ReadBytesBytes(bts, (*z).Args[zb0001])
				if err != nil {
					err = msgp.WrapError(err, "Args", zb0001)
					return
				}
			}
		default:
			err = msgp.ErrNoField(string(field))
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

func (z *ArgsHolder) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *ArgsHolder) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*ArgsHolder)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ArgsHolder) Msgsize() (s int) {
	s = 1 + 2 + msgp.ArrayHeaderSize
	for zb0001 := range (*z).Args {
		s += msgp.BytesPrefixSize + len((*z).Args[zb0001])
	}
	return
}

// MsgIsZero returns whether this is a zero value
func (z *ArgsHolder) MsgIsZero() bool {
	return (len((*z).Args) == 0)
}

// ArgsHolderMaxSize returns a maximum valid message size for this message type
func ArgsHolderMaxSize() (s int) {
	s = 1 + 2
	// Calculating size of slice: z.Args
	s += msgp.ArrayHeaderSize + (argCount * msgp.BytesPrefixSize) + argsTotal
	return
}

// MarshalMsg implements msgp.Marshaler
func (z BoundedArgs) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	if z == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendArrayHeader(o, uint32(len(z)))
	}
	for za0001 := range z {
		o = msgp.AppendBytes(o, z[za0001])
	}
	return
}

func (_ BoundedArgs) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(BoundedArgs)
	if !ok {
		_, ok = (z).(*BoundedArgs)
	}
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BoundedArgs) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var zb0002 int
	var zb0003 bool
	zb0002, zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0002 > argCount {
		err = msgp.ErrOverflow(uint64(zb0002), uint64(argCount))
		err = msgp.WrapError(err)
		return
	}
	if zb0003 {
		(*z) = nil
	} else if (*z) != nil && cap((*z)) >= zb0002 {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(BoundedArgs, zb0002)
	}
	for zb0001 := range *z {
		var zb0004 int
		zb0004, err = msgp.ReadBytesBytesHeader(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		if zb0004 > argMaxSize {
			err = msgp.ErrOverflow(uint64(zb0004), uint64(argMaxSize))
			return
		}
		(*z)[zb0001], bts, err = msgp.ReadBytesBytes(bts, (*z)[zb0001])
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

func (z *BoundedArgs) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *BoundedArgs) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*BoundedArgs)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z BoundedArgs) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for za0001 := range z {
		s += msgp.BytesPrefixSize + len(z[za0001])
	}
	return
}

// MsgIsZero returns whether this is a zero value
func (z BoundedArgs) MsgIsZero() bool {
	return len(z) == 0
}

// BoundedArgsMaxSize returns a maximum valid message size for this message type
func BoundedArgsMaxSize() (s int) {
	// Calculating size of slice: z
	s += msgp.ArrayHeaderSize + ((argCount) * (msgp.BytesPrefixSize + argMaxSize))
	return
}

// MarshalMsg implements msgp.Marshaler
func (z TotalBoundedArgs) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	if z == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendArrayHeader(o, uint32(len(z)))
	}
	for za0001 := range z {
		o = msgp.AppendBytes(o, z[za0001])
	}
	return
}

func (_ TotalBoundedArgs) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(TotalBoundedArgs)
	if !ok {
		_, ok = (z).(*TotalBoundedArgs)
	}
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TotalBoundedArgs) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var zb0002 int
	var zb0003 bool
	zb0002, zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0002 > argCount {
		err = msgp.ErrOverflow(uint64(zb0002), uint64(argCount))
		err = msgp.WrapError(err)
		return
	}
	if zb0003 {
		(*z) = nil
	} else if (*z) != nil && cap((*z)) >= zb0002 {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(TotalBoundedArgs, zb0002)
	}
	for zb0001 := range *z {
		var zb0004 int
		zb0004, err = msgp.ReadBytesBytesHeader(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		if zb0004 > argMaxSize {
			err = msgp.ErrOverflow(uint64(zb0004), uint64(argMaxSize))
			return
		}
		(*z)[zb0001], bts, err = msgp.ReadBytesBytes(bts, (*z)[zb0001])
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

func (z *TotalBoundedArgs) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *TotalBoundedArgs) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*TotalBoundedArgs)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z TotalBoundedArgs) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for za0001 := range z {
		s += msgp.BytesPrefixSize + len(z[za0001])
	}
	return
}

// MsgIsZero returns whether this is a zero value
func (z TotalBoundedArgs) MsgIsZero() bool {
	return len(z) == 0
}

// TotalBoundedArgsMaxSize returns a maximum valid message size for this message type
func TotalBoundedArgsMaxSize() (s int) {
	// Calculating size of slice: z
	s += msgp.ArrayHeaderSize + (argCount * msgp.BytesPrefixSize) + argsTotal
	return
}
