//go:build !skip_msgp_testing

// Code generated by github.com/algorand/msgp DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/algorand/msgp/msgp"

	"github.com/algorand/go-algorand/protocol"
	"github.com/algorand/go-algorand/test/partitiontest"
)

func TestMarshalUnmarshalCompositeRequired(t *testing.T) {
	partitiontest.PartitionTest(t)
	v := CompositeRequired{}
	bts := v.MarshalMsg(nil)
	left, err := v.UnmarshalMsg(bts)
	// The zero value omits its required field(s), so UnmarshalMsg is expected to
	// reject it; only MarshalMsg and Skip are exercised against a zero value.
	if err == nil {
		t.Errorf("expected a missing-required-field error decoding a zero CompositeRequired")
	}

	left, err = msgp.Skip(bts)
	if err != nil {
		t.Fatal(err)
	}
	if len(left) > 0 {
		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
	}
}

func TestRandomizedEncodingCompositeRequired(t *testing.T) {
	protocol.RunEncodingTest(t, &CompositeRequired{})
}

func BenchmarkMarshalMsgCompositeRequired(b *testing.B) {
	v := CompositeRequired{}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		v.MarshalMsg(nil)
	}
}

func BenchmarkAppendMsgCompositeRequired(b *testing.B) {
	v := CompositeRequired{}
	bts := make([]byte, 0, v.Msgsize())
	bts = v.MarshalMsg(bts[0:0])
	b.SetBytes(int64(len(bts)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		bts = v.MarshalMsg(bts[0:0])
	}
}

func BenchmarkUnmarshalCompositeRequired(b *testing.B) {
	v := CompositeRequired{}
	bts := v.MarshalMsg(nil)
	b.ReportAllocs()
	b.SetBytes(int64(len(bts)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		// The zero value fails the required-field check; ignore the error so the
		// benchmark still measures the decoding work.
		_, _ = v.UnmarshalMsg(bts)
	}
}

func TestMarshalUnmarshalInner(t *testing.T) {
	partitiontest.PartitionTest(t)
	v := Inner{}
	bts := v.MarshalMsg(nil)
	left, err := v.UnmarshalMsg(bts)
	if err != nil {
		t.Fatal(err)
	}
	if len(left) > 0 {
		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
	}

	left, err = msgp.Skip(bts)
	if err != nil {
		t.Fatal(err)
	}
	if len(left) > 0 {
		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
	}
}

func TestRandomizedEncodingInner(t *testing.T) {
	protocol.RunEncodingTest(t, &Inner{})
}

func BenchmarkMarshalMsgInner(b *testing.B) {
	v := Inner{}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		v.MarshalMsg(nil)
	}
}

func BenchmarkAppendMsgInner(b *testing.B) {
	v := Inner{}
	bts := make([]byte, 0, v.Msgsize())
	bts = v.MarshalMsg(bts[0:0])
	b.SetBytes(int64(len(bts)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		bts = v.MarshalMsg(bts[0:0])
	}
}

func BenchmarkUnmarshalInner(b *testing.B) {
	v := Inner{}
	bts := v.MarshalMsg(nil)
	b.ReportAllocs()
	b.SetBytes(int64(len(bts)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, err := v.UnmarshalMsg(bts)
		if err != nil {
			b.Fatal(err)
		}
	}
}

func TestMarshalUnmarshalMapRequired(t *testing.T) {
	partitiontest.PartitionTest(t)
	v := MapRequired{}
	bts := v.MarshalMsg(nil)
	left, err := v.UnmarshalMsg(bts)
	// The zero value omits its required field(s), so UnmarshalMsg is expected to
	// reject it; only MarshalMsg and Skip are exercised against a zero value.
	if err == nil {
		t.Errorf("expected a missing-required-field error decoding a zero MapRequired")
	}

	left, err = msgp.Skip(bts)
	if err != nil {
		t.Fatal(err)
	}
	if len(left) > 0 {
		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
	}
}

func TestRandomizedEncodingMapRequired(t *testing.T) {
	protocol.RunEncodingTest(t, &MapRequired{})
}

func BenchmarkMarshalMsgMapRequired(b *testing.B) {
	v := MapRequired{}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		v.MarshalMsg(nil)
	}
}

func BenchmarkAppendMsgMapRequired(b *testing.B) {
	v := MapRequired{}
	bts := make([]byte, 0, v.Msgsize())
	bts = v.MarshalMsg(bts[0:0])
	b.SetBytes(int64(len(bts)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		bts = v.MarshalMsg(bts[0:0])
	}
}

func BenchmarkUnmarshalMapRequired(b *testing.B) {
	v := MapRequired{}
	bts := v.MarshalMsg(nil)
	b.ReportAllocs()
	b.SetBytes(int64(len(bts)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		// The zero value fails the required-field check; ignore the error so the
		// benchmark still measures the decoding work.
		_, _ = v.UnmarshalMsg(bts)
	}
}

func TestMarshalUnmarshalMapRequiredOmitEmpty(t *testing.T) {
	partitiontest.PartitionTest(t)
	v := MapRequiredOmitEmpty{}
	bts := v.MarshalMsg(nil)
	left, err := v.UnmarshalMsg(bts)
	// The zero value omits its required field(s), so UnmarshalMsg is expected to
	// reject it; only MarshalMsg and Skip are exercised against a zero value.
	if err == nil {
		t.Errorf("expected a missing-required-field error decoding a zero MapRequiredOmitEmpty")
	}

	left, err = msgp.Skip(bts)
	if err != nil {
		t.Fatal(err)
	}
	if len(left) > 0 {
		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
	}
}

func TestRandomizedEncodingMapRequiredOmitEmpty(t *testing.T) {
	protocol.RunEncodingTest(t, &MapRequiredOmitEmpty{})
}

func BenchmarkMarshalMsgMapRequiredOmitEmpty(b *testing.B) {
	v := MapRequiredOmitEmpty{}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		v.MarshalMsg(nil)
	}
}

func BenchmarkAppendMsgMapRequiredOmitEmpty(b *testing.B) {
	v := MapRequiredOmitEmpty{}
	bts := make([]byte, 0, v.Msgsize())
	bts = v.MarshalMsg(bts[0:0])
	b.SetBytes(int64(len(bts)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		bts = v.MarshalMsg(bts[0:0])
	}
}

func BenchmarkUnmarshalMapRequiredOmitEmpty(b *testing.B) {
	v := MapRequiredOmitEmpty{}
	bts := v.MarshalMsg(nil)
	b.ReportAllocs()
	b.SetBytes(int64(len(bts)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		// The zero value fails the required-field check; ignore the error so the
		// benchmark still measures the decoding work.
		_, _ = v.UnmarshalMsg(bts)
	}
}

func TestMarshalUnmarshalTupleRequired(t *testing.T) {
	partitiontest.PartitionTest(t)
	v := TupleRequired{}
	bts := v.MarshalMsg(nil)
	left, err := v.UnmarshalMsg(bts)
	// The zero value omits its required field(s), so UnmarshalMsg is expected to
	// reject it; only MarshalMsg and Skip are exercised against a zero value.
	if err == nil {
		t.Errorf("expected a missing-required-field error decoding a zero TupleRequired")
	}

	left, err = msgp.Skip(bts)
	if err != nil {
		t.Fatal(err)
	}
	if len(left) > 0 {
		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
	}
}

func TestRandomizedEncodingTupleRequired(t *testing.T) {
	protocol.RunEncodingTest(t, &TupleRequired{})
}

func BenchmarkMarshalMsgTupleRequired(b *testing.B) {
	v := TupleRequired{}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		v.MarshalMsg(nil)
	}
}

func BenchmarkAppendMsgTupleRequired(b *testing.B) {
	v := TupleRequired{}
	bts := make([]byte, 0, v.Msgsize())
	bts = v.MarshalMsg(bts[0:0])
	b.SetBytes(int64(len(bts)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		bts = v.MarshalMsg(bts[0:0])
	}
}

func BenchmarkUnmarshalTupleRequired(b *testing.B) {
	v := TupleRequired{}
	bts := v.MarshalMsg(nil)
	b.ReportAllocs()
	b.SetBytes(int64(len(bts)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		// The zero value fails the required-field check; ignore the error so the
		// benchmark still measures the decoding work.
		_, _ = v.UnmarshalMsg(bts)
	}
}
