// Code generated by github.com/algorand/msgp DO NOT EDIT.

package tests

import (
	"github.com/algorand/msgp/msgp"
)

// The following msgp objects are implemented in this file:
// CompositeRequired
//         |-----> (*) MarshalMsg
//         |-----> (*) CanMarshalMsg
//         |-----> (*) UnmarshalMsg
//         |-----> (*) UnmarshalMsgWithState
//         |-----> (*) CanUnmarshalMsg
//         |-----> (*) Msgsize
//         |-----> (*) MsgIsZero
//         |-----> CompositeRequiredMaxSize()
//
// Inner
//   |-----> (*) MarshalMsg
//   |-----> (*) CanMarshalMsg
//   |-----> (*) UnmarshalMsg
//   |-----> (*) UnmarshalMsgWithState
//   |-----> (*) CanUnmarshalMsg
//   |-----> (*) Msgsize
//   |-----> (*) MsgIsZero
//   |-----> InnerMaxSize()
//
// MapRequired
//      |-----> (*) MarshalMsg
//      |-----> (*) CanMarshalMsg
//      |-----> (*) UnmarshalMsg
//      |-----> (*) UnmarshalMsgWithState
//      |-----> (*) CanUnmarshalMsg
//      |-----> (*) Msgsize
//      |-----> (*) MsgIsZero
//      |-----> MapRequiredMaxSize()
//
// MapRequiredOmitEmpty
//           |-----> (*) MarshalMsg
//           |-----> (*) CanMarshalMsg
//           |-----> (*) UnmarshalMsg
//           |-----> (*) UnmarshalMsgWithState
//           |-----> (*) CanUnmarshalMsg
//           |-----> (*) Msgsize
//           |-----> (*) MsgIsZero
//           |-----> MapRequiredOmitEmptyMaxSize()
//
// TupleRequired
//       |-----> MarshalMsg
//       |-----> CanMarshalMsg
//       |-----> (*) UnmarshalMsg
//       |-----> (*) UnmarshalMsgWithState
//       |-----> (*) CanUnmarshalMsg
//       |-----> Msgsize
//       |-----> MsgIsZero
//       |-----> TupleRequiredMaxSize()
//

// MarshalMsg implements msgp.Marshaler
func (z *CompositeRequired) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 2 bits */
	if (*z).Nested.X == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len != 0 {
		if (zb0001Mask & 0x2) == 0 { // if not empty
			// string "nested"
			o = append(o, 0xa6, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64)
			// omitempty: check for empty values
			zb0002Len := uint32(1)
			var zb0002Mask uint8 /* 2 bits */
			if (*z).Nested.X == "" {
				zb0002Len--
				zb0002Mask |= 0x2
			}
			// variable map header, size zb0002Len
			o = append(o, 0x80|uint8(zb0002Len))
			if (zb0002Mask & 0x2) == 0 { // if not empty
				// string "x"
				o = append(o, 0xa1, 0x78)
				o = msgp.AppendString(o, (*z).Nested.X)
			}
		}
	}
	return
}

func (_ *CompositeRequired) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(*CompositeRequired)
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompositeRequired) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var field []byte
	_ = field
	var zb0001 int
	var zb0002 bool
	zb0001, zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
	if _, ok := err.(msgp.TypeError); ok {
		zb0001, zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0001 > 0 {
			zb0001--
			var zb0003 int
			var zb0004 bool
			zb0003, zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if _, ok := err.(msgp.TypeError); ok {
				zb0003, zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "struct-from-array", "Nested")
					return
				}
				if zb0003 > 0 {
					zb0003--
					(*z).Nested.X, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "struct-from-array", "Nested", "struct-from-array", "X")
						return
					}
				}
				if zb0003 > 0 {
					err = msgp.ErrTooManyArrayFields(zb0003)
					if err != nil {
						err = msgp.WrapError(err, "struct-from-array", "Nested", "struct-from-array")
						return
					}
				}
			} else {
				if err != nil {
					err = msgp.WrapError(err, "struct-from-array", "Nested")
					return
				}
				if zb0004 {
					(*z).Nested = Inner{}
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "struct-from-array", "Nested")
						return
					}
					switch string(field) {
					case "x":
						(*z).Nested.X, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "struct-from-array", "Nested", "X")
							return
						}
					default:
						err = msgp.ErrNoField(string(field))
						if err != nil {
							err = msgp.WrapError(err, "struct-from-array", "Nested")
							return
						}
					}
				}
			}
		}
		if zb0001 > 0 {
			err = msgp.ErrTooManyArrayFields(zb0001)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array")
				return
			}
		}
	} else {
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0002 {
			(*z) = CompositeRequired{}
		}
		for zb0001 > 0 {
			zb0001--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
			switch string(field) {
			case "nested":
				var zb0005 int
				var zb0006 bool
				zb0005, zb0006, bts, err = msgp.ReadMapHeaderBytes(bts)
				if _, ok := err.(msgp.TypeError); ok {
					zb0005, zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested")
						return
					}
					if zb0005 > 0 {
						zb0005--
						(*z).Nested.X, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Nested", "struct-from-array", "X")
							return
						}
					}
					if zb0005 > 0 {
						err = msgp.ErrTooManyArrayFields(zb0005)
						if err != nil {
							err = msgp.WrapError(err, "Nested", "struct-from-array")
							return
						}
					}
				} else {
					if err != nil {
						err = msgp.WrapError(err, "Nested")
						return
					}
					if zb0006 {
						(*z).Nested = Inner{}
					}
					for zb0005 > 0 {
						zb0005--
						field, bts, err = msgp.ReadMapKeyZC(bts)
						if err != nil {
							err = msgp.WrapError(err, "Nested")
							return
						}
						switch string(field) {
						case "x":
							(*z).Nested.X, bts, err = msgp.ReadStringBytes(bts)
							if err != nil {
								err = msgp.WrapError(err, "Nested", "X")
								return
							}
						default:
							err = msgp.ErrNoField(string(field))
							if err != nil {
								err = msgp.WrapError(err, "Nested")
								return
							}
						}
					}
				}
			default:
				err = msgp.ErrNoField(string(field))
				if err != nil {
					err = msgp.WrapError(err)
					return
				}
			}
		}
	}
	if (*z).Nested.X == "" {
		err = msgp.ErrMissingRequiredField("nested")
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
	}
	o = bts
	return
}

func (z *CompositeRequired) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *CompositeRequired) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*CompositeRequired)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompositeRequired) Msgsize() (s int) {
	s = 1 + 7 + 1 + 2 + msgp.StringPrefixSize + len((*z).Nested.X)
	return
}

// MsgIsZero returns whether this is a zero value
func (z *CompositeRequired) MsgIsZero() bool {
	return ((*z).Nested.X == "")
}

// CompositeRequiredMaxSize returns a maximum valid message size for this message type
func CompositeRequiredMaxSize() (s int) {
	s = 1 + 7 + 1 + 2
	panic("Unable to determine max size: String type z.Nested.X is unbounded")
}

// MarshalMsg implements msgp.Marshaler
func (z *Inner) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 2 bits */
	if (*z).X == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len != 0 {
		if (zb0001Mask & 0x2) == 0 { // if not empty
			// string "x"
			o = append(o, 0xa1, 0x78)
			o = msgp.AppendString(o, (*z).X)
		}
	}
	return
}

func (_ *Inner) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(*Inner)
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Inner) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var field []byte
	_ = field
	var zb0001 int
	var zb0002 bool
	zb0001, zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
	if _, ok := err.(msgp.TypeError); ok {
		zb0001, zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0001 > 0 {
			zb0001--
			(*z).X, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "X")
				return
			}
		}
		if zb0001 > 0 {
			err = msgp.ErrTooManyArrayFields(zb0001)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array")
				return
			}
		}
	} else {
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0002 {
			(*z) = Inner{}
		}
		for zb0001 > 0 {
			zb0001--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
			switch string(field) {
			case "x":
				(*z).X, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "X")
					return
				}
			default:
				err = msgp.ErrNoField(string(field))
				if err != nil {
					err = msgp.WrapError(err)
					return
				}
			}
		}
	}
	o = bts
	return
}

func (z *Inner) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *Inner) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*Inner)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Inner) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len((*z).X)
	return
}

// MsgIsZero returns whether this is a zero value
func (z *Inner) MsgIsZero() bool {
	return ((*z).X == "")
}

// InnerMaxSize returns a maximum valid message size for this message type
func InnerMaxSize() (s int) {
	s = 1 + 2
	panic("Unable to determine max size: String type z.X is unbounded")
}

// MarshalMsg implements msgp.Marshaler
func (z *MapRequired) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 4 bits */
	if (*z).Optional == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if (*z).ReqOmit == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len != 0 {
		if (zb0001Mask & 0x2) == 0 { // if not empty
			// string "opt"
			o = append(o, 0xa3, 0x6f, 0x70, 0x74)
			o = msgp.AppendString(o, (*z).Optional)
		}
		if (zb0001Mask & 0x4) == 0 { // if not empty
			// string "reqomit"
			o = append(o, 0xa7, 0x72, 0x65, 0x71, 0x6f, 0x6d, 0x69, 0x74)
			o = msgp.AppendInt64(o, (*z).ReqOmit)
		}
		// string "reqplain"
		o = append(o, 0xa8, 0x72, 0x65, 0x71, 0x70, 0x6c, 0x61, 0x69, 0x6e)
		o = msgp.AppendString(o, (*z).ReqPlain)
	}
	return
}

func (_ *MapRequired) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(*MapRequired)
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MapRequired) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var field []byte
	_ = field
	var zb0001 int
	var zb0002 bool
	zb0001, zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
	if _, ok := err.(msgp.TypeError); ok {
		zb0001, zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0001 > 0 {
			zb0001--
			(*z).ReqPlain, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "ReqPlain")
				return
			}
		}
		if zb0001 > 0 {
			zb0001--
			(*z).ReqOmit, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "ReqOmit")
				return
			}
		}
		if zb0001 > 0 {
			zb0001--
			(*z).Optional, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "Optional")
				return
			}
		}
		if zb0001 > 0 {
			err = msgp.ErrTooManyArrayFields(zb0001)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array")
				return
			}
		}
	} else {
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0002 {
			(*z) = MapRequired{}
		}
		for zb0001 > 0 {
			zb0001--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
			switch string(field) {
			case "reqplain":
				(*z).ReqPlain, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ReqPlain")
					return
				}
			case "reqomit":
				(*z).ReqOmit, bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ReqOmit")
					return
				}
			case "opt":
				(*z).Optional, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Optional")
					return
				}
			default:
				err = msgp.ErrNoField(string(field))
				if err != nil {
					err = msgp.WrapError(err)
					return
				}
			}
		}
	}
	if (*z).ReqPlain == "" {
		err = msgp.ErrMissingRequiredField("reqplain")
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
	}
	if (*z).ReqOmit == 0 {
		err = msgp.ErrMissingRequiredField("reqomit")
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
	}
	o = bts
	return
}

func (z *MapRequired) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *MapRequired) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*MapRequired)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MapRequired) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len((*z).ReqPlain) + 8 + msgp.Int64Size + 4 + msgp.StringPrefixSize + len((*z).Optional)
	return
}

// MsgIsZero returns whether this is a zero value
func (z *MapRequired) MsgIsZero() bool {
	return ((*z).ReqPlain == "") && ((*z).ReqOmit == 0) && ((*z).Optional == "")
}

// MapRequiredMaxSize returns a maximum valid message size for this message type
func MapRequiredMaxSize() (s int) {
	s = 1 + 9
	panic("Unable to determine max size: String type z.ReqPlain is unbounded")
}

// MarshalMsg implements msgp.Marshaler
func (z *MapRequiredOmitEmpty) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 3 bits */
	if (*z).Optional == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if (*z).Req == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len != 0 {
		if (zb0001Mask & 0x2) == 0 { // if not empty
			// string "opt"
			o = append(o, 0xa3, 0x6f, 0x70, 0x74)
			o = msgp.AppendString(o, (*z).Optional)
		}
		if (zb0001Mask & 0x4) == 0 { // if not empty
			// string "req"
			o = append(o, 0xa3, 0x72, 0x65, 0x71)
			o = msgp.AppendString(o, (*z).Req)
		}
	}
	return
}

func (_ *MapRequiredOmitEmpty) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(*MapRequiredOmitEmpty)
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MapRequiredOmitEmpty) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var field []byte
	_ = field
	var zb0001 int
	var zb0002 bool
	zb0001, zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
	if _, ok := err.(msgp.TypeError); ok {
		zb0001, zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0001 > 0 {
			zb0001--
			(*z).Req, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "Req")
				return
			}
		}
		if zb0001 > 0 {
			zb0001--
			(*z).Optional, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array", "Optional")
				return
			}
		}
		if zb0001 > 0 {
			err = msgp.ErrTooManyArrayFields(zb0001)
			if err != nil {
				err = msgp.WrapError(err, "struct-from-array")
				return
			}
		}
	} else {
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if zb0002 {
			(*z) = MapRequiredOmitEmpty{}
		}
		for zb0001 > 0 {
			zb0001--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
			switch string(field) {
			case "req":
				(*z).Req, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Req")
					return
				}
			case "opt":
				(*z).Optional, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Optional")
					return
				}
			default:
				err = msgp.ErrNoField(string(field))
				if err != nil {
					err = msgp.WrapError(err)
					return
				}
			}
		}
	}
	if (*z).Req == "" {
		err = msgp.ErrMissingRequiredField("req")
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
	}
	o = bts
	return
}

func (z *MapRequiredOmitEmpty) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *MapRequiredOmitEmpty) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*MapRequiredOmitEmpty)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MapRequiredOmitEmpty) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len((*z).Req) + 4 + msgp.StringPrefixSize + len((*z).Optional)
	return
}

// MsgIsZero returns whether this is a zero value
func (z *MapRequiredOmitEmpty) MsgIsZero() bool {
	return ((*z).Req == "") && ((*z).Optional == "")
}

// MapRequiredOmitEmptyMaxSize returns a maximum valid message size for this message type
func MapRequiredOmitEmptyMaxSize() (s int) {
	s = 1 + 4
	panic("Unable to determine max size: String type z.Req is unbounded")
}

// MarshalMsg implements msgp.Marshaler
func (z TupleRequired) MarshalMsg(b []byte) (o []byte) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendString(o, z.A)
	o = msgp.AppendInt64(o, z.B)
	return
}

func (_ TupleRequired) CanMarshalMsg(z interface{}) bool {
	_, ok := (z).(TupleRequired)
	if !ok {
		_, ok = (z).(*TupleRequired)
	}
	return ok
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TupleRequired) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
		err = msgp.ErrMaxDepthExceeded{}
		return
	}
	st.AllowableDepth--
	var zb0001 int
	zb0001, _, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	(*z).A, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "A")
		return
	}
	(*z).B, bts, err = msgp.ReadInt64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "B")
		return
	}
	if (*z).A == "" {
		err = msgp.ErrMissingRequiredField("a")
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
	}
	o = bts
	return
}

func (z *TupleRequired) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *TupleRequired) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*TupleRequired)
	return ok
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z TupleRequired) Msgsize() (s int) {
	s = 1 + msgp.StringPrefixSize + len(z.A) + msgp.Int64Size
	return
}

// MsgIsZero returns whether this is a zero value
func (z TupleRequired) MsgIsZero() bool {
	return (z.A == "") && (z.B == 0)
}

// TupleRequiredMaxSize returns a maximum valid message size for this message type
func TupleRequiredMaxSize() (s int) {
	s = 1
	panic("Unable to determine max size: String type z.A is unbounded")
}
